image: microsoft/dotnet:sdk
stages:
  - build
  - package

build-dotnet:
  stage: build
  tags:
    - short-jobs
  script:
    - dotnet restore
    - dotnet publish -c Release -o build
  artifacts:
    untracked: false
    expire_in: 2 days
    paths:
      - build/

package-into-docker:
  image: docker
  stage: package
  only:
    - /^v[0-9]+.[0-9]+.[0-9]+$/
  except:
    - branches
  dependencies:
    - build-dotnet
  tags:
    - short-jobs
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg CI_VERSION=voting-importer@${CI_COMMIT_REF_NAME} -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - sentry-cli releases new -p voting-importer voting-importer@${CI_COMMIT_REF_NAME}
    - sentry-cli releases set-commits --auto voting-importer@${CI_COMMIT_REF_NAME}
    - sentry-cli upload-dif -p voting-importer -t pdb -t pe .


